name: Mas Hecho
favicon: null
layout_spectrum: 0.99073
typography_spectrum: 0.50675
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b03865'
    - '#f9a11b'
    - '#09426a'
    - '#ff0000'
    - '#ffff00'
  brandStrength: 0.5
  lightness: 0.125
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
