name: Mas Hecho
favicon: null
layout_spectrum: 0.7653334091883153
typography_spectrum: 0.788818807573989
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.605566389625892
  lightness: 0.4692739818710834
  saturation: 0.08304906450212002
  rhythmicContrast: 0.310204440029338
purpose: []
