name: Mas Hecho
favicon: null
layout_spectrum: 0.7653334091883153
typography_spectrum: 0.788818807573989
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b03865'
    - '#f9a11b'
    - '#09426a'
    - '#ff0000'
    - '#ffff00'
  brandStrength: 0.5
  lightness: 0.4692739818710834
  saturation: 0.08304906450212002
  rhythmicContrast: 0.25
purpose: []
